apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workflow.fullname" . }}-env
  labels:
      {{- include "workflow.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
    {{ $key | quote  }}: {{ $value | quote }}
  {{- end }}
