{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "workflow.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "workflow.name" . }}
    helm.sh/chart: {{ include "workflow.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-10"
    {{- with .Values.serviceAccount.extraAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workflow.serviceAccountName" . }}-token
  labels:
    app.kubernetes.io/name: {{ include "workflow.name" . }}
    helm.sh/chart: {{ include "workflow.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
  annotations:
    kubernetes.io/service-account.name: {{ include "workflow.serviceAccountName" . }}
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "workflow.serviceAccountName" . }}-admin
  labels:
    app.kubernetes.io/name: {{ include "workflow.name" . }}
    helm.sh/chart: {{ include "workflow.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "workflow.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
{{- end -}}